name: "Cync LAN Image"
version: "1.0.0"
slug: "cync_lan"
description: "Control Cync lights over LAN using a prebuilt image"
url: "https://github.com/steezywee/cync_lan_image"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
init: false
startup: services
boot: auto
host_network: true
image: "ghcr.io/steezywee/cync_lan_image:latest"
options: {}
schema: {}
